# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16UC9jYakvQ1bjdYNtCliCTFuT1IQDbYq
"""

import streamlit as st
import pickle
import re

st.set_page_config(page_title="Analisis Sentimen MBG", page_icon="🍽️", layout="centered")

st.title("🍽️ Aplikasi Analisis Sentimen Program Makan Bergizi Gratis")
st.write("Aplikasi ini memprediksi sentimen masyarakat menggunakan model Support Vector Machine (SVM).")

# Load Model Pipeline (Otomatis memuat TF-IDF dan SVM)
@st.cache_resource
def load_model():
    with open('svm_tuned_mbg.pkl', 'rb') as f:
        model = pickle.load(f)
    return model

try:
    model_pipeline = load_model()

    user_tweet = st.text_area("Masukkan teks tweet/komentar di sini:", placeholder="Tulis pendapat di sini...")

    if st.button("Analisis Sentimen", type="primary"):
        if user_tweet.strip() != "":
            # Membersihkan teks (opsional & ringan)
            cleaned_tweet = re.sub(r'http\S+|www\.\S+', '', user_tweet)
            cleaned_tweet = re.sub(r'@\w+', '', cleaned_tweet)
            cleaned_tweet = cleaned_tweet.lower()

            # Prediksi langsung menggunakan model pipeline
            prediction = model_pipeline.predict([cleaned_tweet])[0]

            # Tampilkan hasil
            st.subheader("Hasil Analisis:")
            if prediction == 'Positif':
                st.success(f"Sentimen: **{prediction}** 😊🟢")
            elif prediction == 'Negatif':
                st.error(f"Sentimen: **{prediction}** 😡🔴")
            else:
                st.warning(f"Sentimen: **{prediction}** 😐🟡")
        else:
            st.error("Silakan masukkan teks terlebih dahulu!")

except FileNotFoundError:
    st.error("⚠️ Gagal memuat model. Pastikan file 'svm_tuned_mbg.pkl' sudah satu folder dengan file ini.")