# -*- coding: utf-8 -*-
"""Salinan dari PROJEK ML - MBG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uDaMmg0NMXyBKpno1rPR7lrrISnUg-lA

# 🍽️ Analisis Sentimen Program Makan Bergizi Gratis
## Menggunakan Support Vector Machine (SVM) + Komparasi Model

**Alur Kerja:**
1. Instalasi & Import Library
2. Load Data (hasil tweet-harvest)
3. Pra-pemrosesan Data (cleaning teks)
4. Pelabelan Sentimen (IndoBERT)
5. Ekstraksi Fitur (TF-IDF)
6. Pemodelan: SVM, Naive Bayes, Random Forest, Logistic Regression, KNN, Decision Tree, Gradient Boosting
7. Evaluasi & Komparasi Model

---
## 📦 1. Instalasi & Import Library
"""

# Install library yang diperlukan
#!pip install nltk sastrawi pandas numpy scikit-learn matplotlib seaborn wordcloud plotly -q

import pandas as pd
import numpy as np
import re
import string
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from wordcloud import WordCloud
import warnings
warnings.filterwarnings('ignore')

# NLP
import nltk
from nltk.tokenize import word_tokenize
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory

# Machine Learning
from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    classification_report, confusion_matrix,
    accuracy_score, f1_score, precision_score, recall_score
)
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier, AdaBoostClassifier

# Download resource NLTK
nltk.download('punkt', quiet=True)
nltk.download('stopwords', quiet=True)
nltk.download('punkt_tab', quiet=True)

print('✅ Semua library berhasil diimport!')

"""---
## 📂 2. Load Data

> **Catatan:** Data yang digunakan merupakan hasil scraping dari Twitter/X
> menggunakan tweet-harvest dengan beberapa keyword terkait program Makan
> Bergizi Gratis (MBG). Semua file CSV hasil scraping telah digabungkan
> menjadi satu file (`data_mbg_gabungan.csv`) dengan total 5.742 tweet
> setelah penghapusan duplikat.
>
> Upload file `data_mbg_gabungan.csv` ke Google Colab terlebih dahulu.
"""

# ─────────────────────────────────────────────────────────────
# OPSI A: Upload file manual dari komputer lokal
# ─────────────────────────────────────────────────────────────
# from google.colab import files
# uploaded = files.upload()  # pilih file CSV kamu
# import io
# filename = list(uploaded.keys())[0]
# df_raw = pd.read_csv(io.BytesIO(uploaded[filename]))

# ─────────────────────────────────────────────────────────────
# OPSI B: Load dari Google Drive
# ─────────────────────────────────────────────────────────────
#from google.colab import drive
#drive.mount('/content/drive')
#df_raw = pd.read_csv('/content/drive/MyDrive/SEMESTER 2/MACHINE LEARNING/data_mbg_gabungan.csv')
df_raw = pd.read_csv('data_mbg_gabungan.csv')

# ─────────────────────────────────────────────────────────────
# OPSI C: Load dari path lokal (jika sudah di-upload ke Colab)
# ─────────────────────────────────────────────────────────────
# df_raw = pd.read_csv('data_mbg_gabungan.csv')

print(f'✅ Data berhasil dimuat: {df_raw.shape[0]} baris, {df_raw.shape[1]} kolom')
print(f'\n📋 Kolom yang tersedia:')
print(df_raw.columns.tolist())

# Tampilkan 5 baris pertama untuk cek struktur data
df_raw.head()

# Info umum dataset
print('📊 Info Dataset:')
print(df_raw.info())
print('\n📊 Missing Values:')
print(df_raw.isnull().sum())

# ─────────────────────────────────────────────────────────────
# Sesuaikan nama kolom tweet-harvest dengan variabel di bawah ini
# Cek kolom hasil print di atas, lalu sesuaikan:
# ─────────────────────────────────────────────────────────────
KOLOM_TEKS     = 'teks_tweet'       # kolom konten tweet
KOLOM_TANGGAL  = 'created_at'      # kolom tanggal

# Buat dataframe kerja dengan kolom yang dibutuhkan saja
df = df_raw[[KOLOM_TEKS, KOLOM_TANGGAL]].copy()
df.columns = ['teks', 'tanggal']

# Hapus baris dengan teks kosong
df.dropna(subset=['teks'], inplace=True)
df.reset_index(drop=True, inplace=True)

print(f'✅ Data siap: {len(df)} baris')
df.head(3)

"""---
## 🧹 3. Pra-pemrosesan Data

Tahapan cleaning:
1. Hapus duplikat & retweet
2. **Cleaning teks**: hapus URL, mention (@), hashtag (#), emoji, angka, tanda baca
3. Case folding (lowercase)
4. Normalisasi kata gaul/slang
5. Normalisasi huruf berulang (contoh: "bagusssss" → "bagus")
6. Tokenisasi
7. Stopword removal
8. Stemming (Sastrawi)
"""

# ─── 3.1 Hapus Duplikat & Retweet ───────────────────────────
print(f'Sebelum hapus duplikat : {len(df)} baris')

# Hapus retweet (biasanya diawali 'RT @')
df = df[~df['teks'].str.startswith('RT @', na=False)]

# Hapus tweet duplikat
df.drop_duplicates(subset=['teks'], inplace=True)
df.reset_index(drop=True, inplace=True)

print(f'Setelah hapus duplikat : {len(df)} baris')

# ─── 3.2 Kamus Normalisasi Kata Gaul / Slang ────────────────
# Kamu bisa tambahkan lebih banyak kata sesuai data kamu
kamus_slang = {
    'gak': 'tidak', 'ga': 'tidak', 'nggak': 'tidak', 'ngga': 'tidak',
    'tak': 'tidak', 'tdk': 'tidak', 'gk': 'tidak', 'g': 'tidak',
    'yg': 'yang', 'dgn': 'dengan', 'krn': 'karena', 'karna': 'karena',
    'utk': 'untuk', 'tuk': 'untuk', 'buat': 'untuk',
    'udah': 'sudah', 'udh': 'sudah', 'sdh': 'sudah',
    'blm': 'belum', 'blum': 'belum',
    'lg': 'lagi', 'lgi': 'lagi',
    'jg': 'juga', 'juga': 'juga',
    'aja': 'saja', 'aj': 'saja',
    'emg': 'memang', 'emang': 'memang',
    'bgt': 'banget', 'bngt': 'banget',
    'klo': 'kalau', 'klu': 'kalau', 'kl': 'kalau',
    'sy': 'saya', 'gue': 'saya', 'gw': 'saya', 'aku': 'saya',
    'lo': 'kamu', 'lu': 'kamu',
    'hrs': 'harus',
    'bs': 'bisa', 'bsa': 'bisa',
    'dr': 'dari',
    'pd': 'pada',
    'tp': 'tapi', 'tpi': 'tapi',
    'mau': 'ingin', 'mo': 'ingin',
    'bagus': 'baik', 'ok': 'baik', 'oke': 'baik', 'okey': 'baik',
    'jelek': 'buruk', 'ancur': 'buruk', 'parah': 'buruk',
    'mantap': 'bagus', 'mantul': 'bagus', 'keren': 'bagus',
    'wkwk': '', 'wkwkwk': '', 'haha': '', 'hehe': '', 'hihi': '',
    'lol': '', 'kwkwkw': '',
    'mbg': 'makan bergizi gratis',
    'makber': 'makan bergizi',
    'pmb': 'program makan bergizi',
    'prabowo': 'presiden',
}

def normalisasi_slang(teks):
    kata_list = teks.split()
    return ' '.join([kamus_slang.get(kata, kata) for kata in kata_list])

print('✅ Kamus slang siap:', len(kamus_slang), 'kata')

# ─── 3.3 Fungsi Cleaning Teks ────────────────────────────────

def hapus_emoji(teks):
    """Hapus semua emoji dan karakter unicode non-ASCII"""
    # Hapus emoji menggunakan regex unicode range
    emoji_pattern = re.compile(
        "["
        u"\U0001F600-\U0001F64F"  # emoticons
        u"\U0001F300-\U0001F5FF"  # symbols & pictographs
        u"\U0001F680-\U0001F6FF"  # transport & map
        u"\U0001F1E0-\U0001F1FF"  # flags
        u"\U00002702-\U000027B0"
        u"\U000024C2-\U0001F251"
        u"\U0001f926-\U0001f937"
        u"\U00010000-\U0010ffff"
        u"\u2640-\u2642"
        u"\u2600-\u2B55"
        u"\u200d"
        u"\u23cf"
        u"\u23e9"
        u"\u231a"
        u"\ufe0f"
        u"\u3030"
        "]+",
        flags=re.UNICODE
    )
    return emoji_pattern.sub('', teks)

def cleaning_teks(teks):
    """Pipeline cleaning teks lengkap"""
    if pd.isna(teks):
        return ''

    teks = str(teks)

    # 1. Hapus emoji
    teks = hapus_emoji(teks)

    # 2. Hapus URL / link
    teks = re.sub(r'http\S+|www\.\S+|https\S+', '', teks)

    # 3. Hapus mention (@username)
    teks = re.sub(r'@\w+', '', teks)

    # 4. Hapus hashtag (#topic) — hanya simbol #, teksnya dipertahankan
    teks = re.sub(r'#(\w+)', r'\1', teks)

    # 5. Hapus karakter HTML entities
    teks = re.sub(r'&amp;|&lt;|&gt;|&quot;|&#39;', ' ', teks)

    # 6. Hapus angka
    teks = re.sub(r'\d+', '', teks)

    # 7. Hapus tanda baca & karakter khusus
    teks = re.sub(r'[^\w\s]', ' ', teks)

    # 8. Lowercase
    teks = teks.lower()

    # 9. Normalisasi spasi
    teks = re.sub(r'\s+', ' ', teks).strip()

    # 10. Normalisasi huruf berulang (contoh: 'bagusssss' → 'bagus')
    teks = re.sub(r'(.)\1{2,}', r'\1', teks)

    # 11. Normalisasi slang
    teks = normalisasi_slang(teks)

    return teks

# Test cleaning
contoh = "RT @user123: Wah program makan bergizi gratis ini MANTAP BGT!!! 🍛🎉 #MakanBergiziGratis tapi ada yang blm dapat https://t.co/abc123 😢"
print('Sebelum:', contoh)
print('Sesudah:', cleaning_teks(contoh))

# ─── 3.4 Inisialisasi Stemmer & Stopword Bahasa Indonesia ────
factory_stemmer = StemmerFactory()
stemmer = factory_stemmer.create_stemmer()

factory_stop = StopWordRemoverFactory()
stopword_list = factory_stop.get_stop_words()

# Tambahkan stopword kustom yang tidak relevan untuk sentimen MBG
custom_stopwords = [
    'mbg', 'makan', 'bergizi', 'gratis', 'program', 'pemerintah',
    'indonesia', 'anak', 'sekolah', 'siswa', 'saja', 'sudah',
    'juga', 'ini', 'itu', 'ada', 'dengan', 'yang', 'dan', 'di',
    'ke', 'dari', 'untuk', 'pada', 'dalam', 'akan', 'tidak', 'bisa'
    # Catatan: 'tidak' sengaja tidak dihapus karena penting untuk sentimen negatif
    # Kamu bisa sesuaikan berdasarkan hasil analisis awal
]

# Gabungkan dan buat set untuk lookup cepat
semua_stopword = set(stopword_list) | set(custom_stopwords)

def tokenize_dan_clean(teks):
    """Tokenisasi, hapus stopword, dan stemming"""
    if not teks or teks.strip() == '':
        return ''
    tokens = word_tokenize(teks)
    tokens = [t for t in tokens if t not in semua_stopword and len(t) > 2]
    tokens = [stemmer.stem(t) for t in tokens]
    return ' '.join(tokens)

print('✅ Stemmer & stopword siap')

# ─── 3.5 Jalankan Semua Tahap Pra-pemrosesan ────────────────
print('⏳ Memproses data... (mungkin perlu beberapa menit untuk data besar)')

# Step 1: Cleaning dasar
df['teks_clean'] = df['teks'].apply(cleaning_teks)
print('✅ Step 1: Cleaning selesai')

# Step 2: Tokenisasi + stopword removal + stemming
df['teks_proses'] = df['teks_clean'].apply(tokenize_dan_clean)
print('✅ Step 2: Tokenisasi + Stemming selesai')

# Hapus baris yang teksnya kosong setelah proses
df = df[df['teks_proses'].str.strip() != '']
df.reset_index(drop=True, inplace=True)

print(f'\n📊 Total data siap diproses: {len(df)} tweets')

# Tampilkan perbandingan
df[['teks', 'teks_clean', 'teks_proses']].head(5)

"""---
## 🏷️ 5. Pelabelan Sentimen (IndoBERT)

Pelabelan dilakukan **setelah** data bersih menggunakan model **IndoBERT**
(*Indonesian RoBERTa Base Sentiment Classifier*), yaitu model deep learning
berbasis transformer yang telah dilatih khusus untuk analisis sentimen
Bahasa Indonesia.

**Metode:** Setiap tweet diproses oleh model IndoBERT yang secara otomatis
mengklasifikasikan teks ke dalam tiga label: **Positif**, **Negatif**, atau **Netral**.
Proses dilakukan secara batch (32 tweet sekaligus) untuk efisiensi dengan
memanfaatkan GPU.

> ⚠️ **Keunggulan dibanding lexicon-based:** IndoBERT mampu memahami konteks
> kalimat secara keseluruhan sehingga lebih akurat dalam mendeteksi sarkasme
> dan kalimat ambigu yang umum ditemukan di Twitter/X.
"""

# Install library
#!pip install transformers torch -q

from transformers import pipeline
import torch

# Cek GPU tersedia
print(f'GPU tersedia: {torch.cuda.is_available()}')

# Load model IndoBERT sentimen Bahasa Indonesia
print('⏳ Loading model IndoBERT...')
sentiment_pipeline = pipeline(
    "text-classification",
    model="w11wo/indonesian-roberta-base-sentiment-classifier",
    tokenizer="w11wo/indonesian-roberta-base-sentiment-classifier",
    device=0 if torch.cuda.is_available() else -1  # 0 = GPU, -1 = CPU
)
print('✅ Model berhasil dimuat!')

from tqdm import tqdm

def label_indobert(teks):
    if not teks or str(teks).strip() == '':
        return 'Netral'
    try:
        hasil = sentiment_pipeline(str(teks)[:512])[0]
        label = hasil['label'].lower()
        if label == 'positive':
            return 'Positif'
        elif label == 'negative':
            return 'Negatif'
        else:
            return 'Netral'
    except:
        return 'Netral'

# Labeling semua tweet sekaligus pakai batch (lebih cepat)
print('⏳ Melabeli data dengan IndoBERT...')

teks_list = df['teks_clean'].fillna('').tolist()
hasil_label = []

# Proses per batch 32 biar tidak kehabisan memori GPU
batch_size = 32
for i in tqdm(range(0, len(teks_list), batch_size)):
    batch = [t[:512] if t.strip() != '' else 'netral' for t in teks_list[i:i+batch_size]]
    try:
        hasil_batch = sentiment_pipeline(batch)
        for h in hasil_batch:
            label = h['label'].lower()
            if label == 'positive':
                hasil_label.append('Positif')
            elif label == 'negative':
                hasil_label.append('Negatif')
            else:
                hasil_label.append('Netral')
    except:
        hasil_label.extend(['Netral'] * len(batch))

df['sentimen'] = hasil_label

print('\n✅ Pelabelan selesai!')
print('\n📊 Distribusi Sentimen:')
print(df['sentimen'].value_counts())
print()
print('Persentase:')
print(df['sentimen'].value_counts(normalize=True).mul(100).round(2).astype(str) + '%')

# Visualisasi distribusi sentimen
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Pie chart
sentimen_counts = df['sentimen'].value_counts()
colors = {'Positif': '#2ecc71', 'Negatif': '#e74c3c', 'Netral': '#95a5a6'}
color_list = [colors.get(s, 'gray') for s in sentimen_counts.index]

axes[0].pie(sentimen_counts.values, labels=sentimen_counts.index,
            autopct='%1.1f%%', colors=color_list, startangle=90,
            wedgeprops={'edgecolor': 'white', 'linewidth': 2})
axes[0].set_title('Distribusi Sentimen (Pie Chart)', fontweight='bold')

# Bar chart
bars = axes[1].bar(sentimen_counts.index, sentimen_counts.values,
                   color=color_list, edgecolor='white', linewidth=1.5)
for bar, val in zip(bars, sentimen_counts.values):
    axes[1].text(bar.get_x() + bar.get_width()/2, bar.get_height() + 5,
                 str(val), ha='center', fontweight='bold')
axes[1].set_title('Distribusi Sentimen (Bar Chart)', fontweight='bold')
axes[1].set_ylabel('Jumlah Tweet')

plt.suptitle('Analisis Sentimen Program Makan Bergizi Gratis', fontsize=14, fontweight='bold', y=1.02)
plt.tight_layout()
plt.savefig('distribusi_sentimen.png', dpi=150, bbox_inches='tight')
plt.show()

# ─── 5.3 WordCloud per Sentimen ─────────────────────────────
fig, axes = plt.subplots(1, 3, figsize=(18, 5))
sentimen_list = ['Positif', 'Negatif', 'Netral']
wc_colors = {'Positif': 'Greens', 'Negatif': 'Reds', 'Netral': 'Blues'}

for ax, sent in zip(axes, sentimen_list):
    teks_gabung = ' '.join(df[df['sentimen'] == sent]['teks_proses'].dropna())
    if teks_gabung.strip():
        wc = WordCloud(
            width=400, height=300,
            background_color='white',
            colormap=wc_colors[sent],
            max_words=80
        ).generate(teks_gabung)
        ax.imshow(wc, interpolation='bilinear')
    ax.axis('off')
    ax.set_title(f'WordCloud - {sent}', fontweight='bold', fontsize=12)

plt.suptitle('Kata yang Sering Muncul per Sentimen', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.savefig('wordcloud_sentimen.png', dpi=150, bbox_inches='tight')
plt.show()

# ─── 5.4 Simpan Dataset Berlabel ────────────────────────────
df_export = df[['teks', 'teks_clean', 'teks_proses', 'tanggal', 'sentimen']]
df_export.to_csv('data_berlabel.csv', index=False)
print(f'✅ Dataset berlabel tersimpan: data_berlabel.csv ({len(df_export)} baris)')
df_export.head(5)

"""---
## 🤖 6. Pemodelan Machine Learning

### Tahapan:
1. Ekstraksi fitur dengan **TF-IDF**
2. Split data training & testing (80:20)
3. Latih model: **SVM**, **Naive Bayes**, **Random Forest**, **Logistic Regression**, **KNN**, **Decision Tree**, **Gradient Boosting**
4. Evaluasi & komparasi performa
"""

# ─── 6.1 Persiapan Data untuk Pemodelan ─────────────────────

# Gunakan teks_proses (sudah di-stemming) sebagai fitur
# Hapus kelas Netral jika sampelnya terlalu sedikit (opsional)
# df_model = df[df['sentimen'] != 'Netral'].copy()  # hapus netral
df_model = df.copy()  # pakai semua kelas

X = df_model['teks_proses']
y = df_model['sentimen']

print('📊 Distribusi kelas:')
print(y.value_counts())
print(f'\nTotal data: {len(X)}')

# Cek apakah data cukup seimbang
# Jika tidak seimbang, pertimbangkan oversampling (SMOTE) atau class_weight='balanced'

# ─── 6.2 Ekstraksi Fitur TF-IDF ─────────────────────────────
tfidf = TfidfVectorizer(
    max_features=5000,     # ambil 5000 fitur teratas
    ngram_range=(1, 2),    # unigram + bigram
    min_df=2,              # abaikan kata yang muncul < 2 kali
    max_df=0.95,           # abaikan kata yang muncul di > 95% dokumen
    sublinear_tf=True      # log normalization untuk TF
)

# Split data dulu BARU fit TF-IDF (untuk mencegah data leakage)
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y  # pastikan proporsi kelas sama di train & test
)

# Fit TF-IDF pada data training, transform keduanya
X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf  = tfidf.transform(X_test)

print(f'✅ TF-IDF selesai')
print(f'   Training set : {X_train_tfidf.shape}')
print(f'   Testing set  : {X_test_tfidf.shape}')

# ─── 6.3 Fungsi Evaluasi Model ──────────────────────────────
def evaluasi_model(nama, model, X_tr, X_te, y_tr, y_te):
    """Latih model dan kembalikan metrik evaluasi"""
    model.fit(X_tr, y_tr)
    y_pred = model.predict(X_te)

    acc  = accuracy_score(y_te, y_pred)
    prec = precision_score(y_te, y_pred, average='weighted', zero_division=0)
    rec  = recall_score(y_te, y_pred, average='weighted', zero_division=0)
    f1   = f1_score(y_te, y_pred, average='weighted', zero_division=0)

    print(f'\n{'='*55}')
    print(f'  MODEL: {nama}')
    print(f'{'='*55}')
    print(f'  Accuracy  : {acc:.4f} ({acc*100:.2f}%)')
    print(f'  Precision : {prec:.4f}')
    print(f'  Recall    : {rec:.4f}')
    print(f'  F1-Score  : {f1:.4f}')
    print(f'\n  Classification Report:')
    print(classification_report(y_te, y_pred, zero_division=0))

    return {
        'Model': nama, 'Accuracy': acc, 'Precision': prec,
        'Recall': rec, 'F1-Score': f1, 'y_pred': y_pred, 'model_obj': model
    }

hasil_semua = []

# ─── 6.4 MODEL 1: Support Vector Machine (SVM) ──────────────
# SVM dengan kernel RBF (cocok untuk teks)
svm_model = SVC(
    kernel='linear',       # 'linear' biasanya terbaik untuk teks
    C=1.0,                 # parameter regularisasi
    class_weight='balanced', # handle imbalanced class
    random_state=42
)

hasil_svm = evaluasi_model(
    'SVM (Linear)',
    svm_model,
    X_train_tfidf, X_test_tfidf, y_train, y_test
)
hasil_semua.append({k: v for k, v in hasil_svm.items() if k not in ['y_pred', 'model_obj']})

# ─── 6.5 MODEL 2: Naive Bayes ───────────────────────────────
nb_model = MultinomialNB(
    alpha=1.0  # Laplace smoothing
)

# Catatan: MultinomialNB memerlukan nilai non-negatif
# TF-IDF dengan sublinear_tf bisa menghasilkan nilai negatif → gunakan abs atau MinMaxScaler
from sklearn.preprocessing import MinMaxScaler
from scipy.sparse import csr_matrix

scaler_nb = MinMaxScaler()
X_train_nb = csr_matrix(scaler_nb.fit_transform(X_train_tfidf.toarray()))
X_test_nb  = csr_matrix(scaler_nb.transform(X_test_tfidf.toarray()))

hasil_nb = evaluasi_model(
    'Naive Bayes (Multinomial)',
    nb_model,
    X_train_nb, X_test_nb, y_train, y_test
)
hasil_semua.append({k: v for k, v in hasil_nb.items() if k not in ['y_pred', 'model_obj']})

# ─── 6.6 MODEL 3: Random Forest ─────────────────────────────
rf_model = RandomForestClassifier(
    n_estimators=100,
    max_depth=None,
    class_weight='balanced',
    random_state=42,
    n_jobs=-1  # gunakan semua core CPU
)

hasil_rf = evaluasi_model(
    'Random Forest',
    rf_model,
    X_train_tfidf, X_test_tfidf, y_train, y_test
)
hasil_semua.append({k: v for k, v in hasil_rf.items() if k not in ['y_pred', 'model_obj']})

# ─── MODEL 4: Logistic Regression ───────────────────────────
lr_model = LogisticRegression(max_iter=1000, class_weight='balanced', random_state=42)
hasil_lr = evaluasi_model('Logistic Regression', lr_model,
                           X_train_tfidf, X_test_tfidf, y_train, y_test)
hasil_semua.append({k: v for k, v in hasil_lr.items() if k not in ['y_pred', 'model_obj']})

# ─── MODEL 5: K-Nearest Neighbor ────────────────────────────
knn_model = KNeighborsClassifier(n_neighbors=5)
hasil_knn = evaluasi_model('KNN', knn_model,
                            X_train_tfidf, X_test_tfidf, y_train, y_test)
hasil_semua.append({k: v for k, v in hasil_knn.items() if k not in ['y_pred', 'model_obj']})

# ─── MODEL 6: Decision Tree ──────────────────────────────────
dt_model = DecisionTreeClassifier(class_weight='balanced', random_state=42)
hasil_dt = evaluasi_model('Decision Tree', dt_model,
                           X_train_tfidf, X_test_tfidf, y_train, y_test)
hasil_semua.append({k: v for k, v in hasil_dt.items() if k not in ['y_pred', 'model_obj']})

# ─── MODEL 7: Gradient Boosting ──────────────────────────────
gb_model = GradientBoostingClassifier(n_estimators=100, random_state=42)
hasil_gb = evaluasi_model('Gradient Boosting', gb_model,
                           X_train_tfidf, X_test_tfidf, y_train, y_test)
hasil_semua.append({k: v for k, v in hasil_gb.items() if k not in ['y_pred', 'model_obj']})

"""---
## 📊 7. Komparasi & Evaluasi Model

Tahap ini membandingkan performa seluruh model yang telah dilatih berdasarkan
empat metrik evaluasi utama:
- **Accuracy**: persentase prediksi yang benar secara keseluruhan
- **Precision**: ketepatan prediksi per kelas
- **Recall**: kemampuan model menangkap semua data yang benar per kelas
- **F1-Score**: rata-rata harmonis antara precision dan recall

Selain itu dilakukan **5-fold Cross Validation** untuk memastikan hasil
evaluasi lebih robust dan tidak bergantung pada satu pembagian data saja.
"""

# ─── 7.1 Tabel Komparasi ────────────────────────────────────
df_komparasi = pd.DataFrame(hasil_semua)
df_komparasi = df_komparasi.set_index('Model')
df_komparasi = df_komparasi.round(4)

print('\n📊 TABEL KOMPARASI MODEL')
print('='*60)
print(df_komparasi.to_string())
print('='*60)
print(f'\n🏆 Model Terbaik (Accuracy): {df_komparasi["Accuracy"].idxmax()}')
print(f'🏆 Model Terbaik (F1-Score): {df_komparasi["F1-Score"].idxmax()}')

# ─── 7.2 Visualisasi Komparasi Model ────────────────────────
metrics = ['Accuracy', 'Precision', 'Recall', 'F1-Score']
x = np.arange(len(df_komparasi.index))
width = 0.2

fig, ax = plt.subplots(figsize=(13, 6))
palette = ['#3498db', '#e74c3c', '#2ecc71', '#f39c12']

for i, (metric, color) in enumerate(zip(metrics, palette)):
    bars = ax.bar(x + i*width, df_komparasi[metric], width,
                  label=metric, color=color, alpha=0.85)
    for bar in bars:
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.005,
                f'{bar.get_height():.3f}', ha='center', fontsize=8)

ax.set_xlabel('Model', fontsize=12)
ax.set_ylabel('Skor', fontsize=12)
ax.set_title('Komparasi Performa Model Klasifikasi Sentimen', fontsize=14, fontweight='bold')
ax.set_xticks(x + width * 1.5)
ax.set_xticklabels(df_komparasi.index, fontsize=11)
ax.set_ylim(0, 1.1)
ax.legend(loc='upper right', fontsize=10)
ax.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.savefig('komparasi_model.png', dpi=150, bbox_inches='tight')
plt.show()

# ─── Tambahan: MSE per Model ─────────────────────────────────
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_squared_error

le = LabelEncoder()
le.fit(y_test)
y_test_num = le.transform(y_test)

mse_results = []

model_preds = [
    ('SVM (Linear)',        hasil_svm['y_pred']),
    ('Naive Bayes',         hasil_nb['y_pred']),
    ('Random Forest',       hasil_rf['y_pred']),
    ('Logistic Regression', hasil_lr['y_pred']),
    ('KNN',                 hasil_knn['y_pred']),
    ('Decision Tree',       hasil_dt['y_pred']),
    ('Gradient Boosting',   hasil_gb['y_pred']),
]

print('📊 MSE per Model:')
print('='*45)
for nama, y_pred in model_preds:
    y_pred_num = le.transform(y_pred)
    mse = mean_squared_error(y_test_num, y_pred_num)
    mse_results.append({'Model': nama, 'MSE': round(mse, 4)})
    print(f'  {nama:<25}: {mse:.4f}')

print('='*45)
print(f'\n✅ Model dengan MSE terendah: {min(mse_results, key=lambda x: x["MSE"])["Model"]}')

# ─── 7.3 Confusion Matrix untuk Setiap Model ────────────────
model_info = [
    ('SVM (Linear)', hasil_svm['y_pred']),
    ('Naive Bayes', hasil_nb['y_pred']),
    ('Random Forest', hasil_rf['y_pred']),
    ('Logistic Regression', hasil_lr['y_pred']),
    ('KNN',               hasil_knn['y_pred']),
    ('Decision Tree',     hasil_dt['y_pred']),
    ('Gradient Boosting', hasil_gb['y_pred']),
]

label_kelas = sorted(y_test.unique())
fig, axes = plt.subplots(2, 4, figsize=(24, 10))
axes = axes.flatten()

for ax, (nama, y_pred) in zip(axes, model_info):
    cm = confusion_matrix(y_test, y_pred, labels=label_kelas)
    sns.heatmap(
        cm, annot=True, fmt='d', cmap='Blues',
        xticklabels=label_kelas, yticklabels=label_kelas, ax=ax
    )
    ax.set_title(f'Confusion Matrix\n{nama}', fontweight='bold')
    ax.set_xlabel('Prediksi')
    ax.set_ylabel('Aktual')

plt.tight_layout()
plt.savefig('confusion_matrix.png', dpi=150, bbox_inches='tight')
plt.show()

# ─── 7.4 Cross Validation (opsional, lebih robust) ──────────
print('⏳ Melakukan 5-fold cross validation...')

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# Gunakan pipeline agar tidak ada data leakage
from sklearn.pipeline import Pipeline

tfidf_cv = TfidfVectorizer(max_features=5000, ngram_range=(1, 2), sublinear_tf=True)

pipelines = {
    'SVM (Linear)' : Pipeline([('tfidf', TfidfVectorizer(max_features=5000, ngram_range=(1,2), sublinear_tf=True)),
                                ('clf', SVC(kernel='linear', class_weight='balanced', random_state=42))]),
    'Naive Bayes'  : Pipeline([('tfidf', TfidfVectorizer(max_features=5000, ngram_range=(1,2))),
                                ('clf', MultinomialNB())]),
    'Random Forest': Pipeline([('tfidf', TfidfVectorizer(max_features=5000, ngram_range=(1,2), sublinear_tf=True)),
                                ('clf', RandomForestClassifier(n_estimators=100, class_weight='balanced', random_state=42, n_jobs=-1))]),
    'Logistic Regression': Pipeline([('tfidf', TfidfVectorizer(max_features=5000, ngram_range=(1,2), sublinear_tf=True)),
                                     ('clf', LogisticRegression(max_iter=1000, class_weight='balanced', random_state=42))]),
    'Decision Tree'      : Pipeline([('tfidf', TfidfVectorizer(max_features=5000, ngram_range=(1,2), sublinear_tf=True)),
                                     ('clf', DecisionTreeClassifier(class_weight='balanced', random_state=42))]),
    'Gradient Boosting'  : Pipeline([('tfidf', TfidfVectorizer(max_features=5000, ngram_range=(1,2), sublinear_tf=True)),
                                     ('clf', GradientBoostingClassifier(n_estimators=100, random_state=42))]),
}

cv_results = {}
for nama, pipeline in pipelines.items():
    scores = cross_val_score(pipeline, X, y, cv=cv, scoring='accuracy', n_jobs=-1)
    cv_results[nama] = scores
    print(f'  {nama}: {scores.mean():.4f} ± {scores.std():.4f}')

print('\n✅ Cross Validation selesai')

# ─── 7.5 Cek Overfitting & Underfitting ─────────────────────
print('⏳ Mengecek overfitting/underfitting...')

hasil_overfit = []

model_list = [
    ('SVM (Linear)',        SVC(kernel='linear', class_weight='balanced', random_state=42)),
    ('Naive Bayes',         MultinomialNB()),
    ('Random Forest',       RandomForestClassifier(n_estimators=100, class_weight='balanced', random_state=42, n_jobs=-1)),
    ('Logistic Regression', LogisticRegression(max_iter=1000, class_weight='balanced', random_state=42)),
    ('KNN',                 KNeighborsClassifier(n_neighbors=5)),
    ('Decision Tree',       DecisionTreeClassifier(class_weight='balanced', random_state=42)),
    ('Gradient Boosting',   GradientBoostingClassifier(n_estimators=100, random_state=42)),
]

for nama, model in model_list:
    # Khusus Naive Bayes pakai X_train_nb
    if nama == 'Naive Bayes':
        model.fit(X_train_nb, y_train)
        train_acc = accuracy_score(y_train, model.predict(X_train_nb))
        test_acc  = accuracy_score(y_test,  model.predict(X_test_nb))
    else:
        model.fit(X_train_tfidf, y_train)
        train_acc = accuracy_score(y_train, model.predict(X_train_tfidf))
        test_acc  = accuracy_score(y_test,  model.predict(X_test_tfidf))

    selisih = train_acc - test_acc

    if selisih > 0.1:
        status = '⚠️ Overfitting'
    elif test_acc < 0.6:
        status = '⚠️ Underfitting'
    else:
        status = '✅ Normal'

    hasil_overfit.append({
        'Model': nama,
        'Train Accuracy': round(train_acc, 4),
        'Test Accuracy' : round(test_acc, 4),
        'Selisih'       : round(selisih, 4),
        'Status'        : status
    })

df_overfit = pd.DataFrame(hasil_overfit)
print('\n📊 Hasil Pengecekan Overfitting/Underfitting:')
print(df_overfit.to_string(index=False))

# Visualisasi Train vs Test Accuracy
fig, ax = plt.subplots(figsize=(13, 6))

x = np.arange(len(df_overfit))
width = 0.35

bars_train = ax.bar(x - width/2, df_overfit['Train Accuracy'], width,
                    label='Train Accuracy', color='#3498db', alpha=0.85)
bars_test  = ax.bar(x + width/2, df_overfit['Test Accuracy'],  width,
                    label='Test Accuracy',  color='#e74c3c', alpha=0.85)

# Label angka di atas bar
for bar in bars_train:
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.005,
            f'{bar.get_height():.3f}', ha='center', fontsize=8)
for bar in bars_test:
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.005,
            f'{bar.get_height():.3f}', ha='center', fontsize=8)

ax.set_xticks(x)
ax.set_xticklabels(df_overfit['Model'], rotation=15, ha='right', fontsize=10)
ax.set_ylabel('Accuracy', fontsize=12)
ax.set_ylim(0, 1.15)
ax.set_title('Perbandingan Train vs Test Accuracy\n(Deteksi Overfitting/Underfitting)',
             fontsize=13, fontweight='bold')
ax.legend(fontsize=11)
ax.grid(axis='y', alpha=0.3)
ax.axhline(y=0.6, color='orange', linestyle='--', alpha=0.5, label='Batas Underfitting (0.6)')

plt.tight_layout()
plt.savefig('overfitting_check.png', dpi=150, bbox_inches='tight')
plt.show()

# ─── 7.6 Top Fitur TF-IDF per Sentimen ──────────────────────
import numpy as np

fig, axes = plt.subplots(1, 3, figsize=(18, 6))
sentimen_list = ['Positif', 'Negatif', 'Netral']
colors = {'Positif': '#2ecc71', 'Negatif': '#e74c3c', 'Netral': '#95a5a6'}

fitur_nama = np.array(tfidf.get_feature_names_out())

for ax, sentimen in zip(axes, sentimen_list):
    # Ambil index tweet dengan sentimen tertentu di data training
    idx = y_train[y_train == sentimen].index

    # Ambil vektor TF-IDF untuk kelas tersebut dan hitung rata-rata
    X_kelas = X_train_tfidf[y_train.index.get_indexer(idx)]
    skor_rata = np.asarray(X_kelas.mean(axis=0)).flatten()

    # Ambil top 15 kata
    top_idx = skor_rata.argsort()[-15:][::-1]
    top_kata = fitur_nama[top_idx]
    top_skor = skor_rata[top_idx]

    # Plot
    ax.barh(top_kata[::-1], top_skor[::-1], color=colors[sentimen], alpha=0.85)
    ax.set_title(f'Top 15 Kata — {sentimen}', fontweight='bold', fontsize=12)
    ax.set_xlabel('Rata-rata Skor TF-IDF')
    ax.grid(axis='x', alpha=0.3)

plt.suptitle('Kata Paling Berpengaruh per Sentimen (TF-IDF)',
             fontsize=14, fontweight='bold')
plt.tight_layout()
plt.savefig('top_fitur_tfidf.png', dpi=150, bbox_inches='tight')
plt.show()

# ─── 7.7 Analisis Kesalahan Prediksi (Error Analysis) ────────

# Ambil data test beserta prediksi SVM
df_test = X_test.reset_index(drop=True).to_frame(name='teks_proses')
df_test['label_asli']    = y_test.reset_index(drop=True)
df_test['label_prediksi'] = hasil_svm['y_pred']

# Filter yang salah prediksi
df_salah = df_test[df_test['label_asli'] != df_test['label_prediksi']].copy()
df_salah = df_salah.reset_index(drop=True)

print(f'📊 Total prediksi salah : {len(df_salah)} dari {len(df_test)} data test')
print(f'   Error rate           : {len(df_salah)/len(df_test)*100:.2f}%')
print()

# Distribusi kesalahan per kombinasi label
print('📋 Pola Kesalahan (Label Asli → Label Prediksi):')
pola_salah = df_salah.groupby(['label_asli', 'label_prediksi']).size().reset_index(name='jumlah')
pola_salah = pola_salah.sort_values('jumlah', ascending=False)
print(pola_salah.to_string(index=False))
print()

# Tampilkan contoh tweet yang salah prediksi per kombinasi
print('📝 Contoh Tweet yang Salah Diprediksi:\n')
for _, row in pola_salah.iterrows():
    asli  = row['label_asli']
    pred  = row['label_prediksi']
    jml   = row['jumlah']
    contoh = df_salah[
        (df_salah['label_asli'] == asli) &
        (df_salah['label_prediksi'] == pred)
    ]['teks_proses'].head(3).tolist()

    print(f'  ❌ {asli} → diprediksi {pred} ({jml} tweet)')
    for i, t in enumerate(contoh, 1):
        print(f'     {i}. {t[:100]}...' if len(t) > 100 else f'     {i}. {t}')
    print()

# Visualisasi pola kesalahan sebagai heatmap
pivot_salah = pola_salah.pivot(index='label_asli', columns='label_prediksi', values='jumlah').fillna(0)

plt.figure(figsize=(7, 5))
sns.heatmap(
    pivot_salah, annot=True, fmt='.0f',
    cmap='Oranges', linewidths=0.5, linecolor='white',
    cbar_kws={'label': 'Jumlah Tweet Salah Prediksi'}
)
plt.title('Pola Kesalahan Prediksi Model SVM', fontsize=13, fontweight='bold')
plt.xlabel('Label Prediksi')
plt.ylabel('Label Asli')
plt.tight_layout()
plt.savefig('error_analysis.png', dpi=150, bbox_inches='tight')
plt.show()

"""---
## 🏆 Kesimpulan: Model Terbaik untuk Dataset MBG

Berdasarkan seluruh hasil evaluasi, **SVM (Linear)** ditetapkan sebagai model
terbaik untuk klasifikasi sentimen dataset tweet Program Makan Bergizi Gratis ini.

### Ringkasan Performa Semua Model

| Model | Accuracy | Precision | Recall | F1-Score | CV Score | Status |
|---|---|---|---|---|---|---|
| **SVM (Linear)** | **0,7386** | **0,7441** | **0,7386** | **0,7391** | 0,7350 ± 0,0064 | ⚠️ Overfitting moderat |
| Logistic Regression | 0,7386 | 0,7425 | 0,7386 | 0,7386 | **0,7397 ± 0,0081** | ⚠️ Overfitting moderat |
| Naive Bayes | 0,7026 | 0,7342 | 0,7026 | 0,7009 | 0,7183 ± 0,0130 | ✅ Normal |
| Random Forest | 0,7000 | 0,7002 | 0,7000 | 0,6987 | 0,7060 ± 0,0119 | ⚠️ Overfitting |
| Gradient Boosting | 0,6851 | 0,6887 | 0,6851 | 0,6823 | 0,6753 ± 0,0100 | ✅ Normal |
| Decision Tree | 0,6061 | 0,6043 | 0,6061 | 0,6045 | 0,5927 ± 0,0114 | ⚠️ Overfitting parah |
| KNN | 0,4430 | 0,4509 | 0,4430 | 0,4243 | - | ⚠️ Overfitting + Underfitting |

### Alasan SVM sebagai Model Terbaik

**1. Accuracy dan F1-Score tertinggi (73,86% dan 0,7391)**
SVM bersama Logistic Regression memperoleh akurasi tertinggi. Namun SVM
unggul tipis pada Precision (0,7441 vs 0,7425) dan F1-Score (0,7391 vs 0,7386)
yang merupakan metrik paling relevan untuk klasifikasi teks multikelas.

**2. Performa paling konsisten lintas semua metrik**
Nilai Precision, Recall, dan F1-Score SVM semuanya berada di rentang 0,73–0,74
secara merata, menunjukkan model tidak bias terhadap kelas tertentu dan mampu
mendeteksi ketiga sentimen (Positif, Negatif, Netral) secara seimbang.

**3. Standar deviasi cross validation terkecil (±0,0064)**
Nilai standar deviasi SVM pada 5-fold cross validation adalah yang terkecil
di antara semua model, menunjukkan performa yang paling stabil dan konsisten
terlepas dari variasi pembagian data.

**4. Cocok untuk data teks berdimensi tinggi**
TF-IDF menghasilkan 5.000 fitur — SVM dirancang khusus untuk bekerja optimal
pada ruang fitur berdimensi tinggi dengan mencari hyperplane pemisah terbaik
antar kelas sentimen.

**5. Overfitting masih dalam batas wajar**
Meskipun menunjukkan overfitting moderat (selisih train-test 0,1712), nilai
ini jauh lebih rendah dibanding Decision Tree (0,3884) dan Random Forest (0,2945).
Test accuracy SVM yang tetap tertinggi membuktikan model masih mampu
menggeneralisasi dengan baik pada data baru.

### Kesimpulan

Kombinasi **TF-IDF + SVM kernel linear** terbukti menjadi pendekatan terbaik
untuk klasifikasi sentimen tweet berbahasa Indonesia tentang Program Makan
Bergizi Gratis. Hasil ini sejalan dengan penelitian-penelitian analisis sentimen
teks bahasa Indonesia yang secara konsisten menunjukkan keunggulan SVM dalam
menangani data teks informal berdimensi tinggi.

---
## 🔧 8. Hyperparameter Tuning Model SVM (Terbaik)

Setelah komparasi model, **SVM (Linear)** terpilih sebagai model terbaik.
Pada tahap ini dilakukan **hyperparameter tuning** untuk memaksimalkan
performa SVM menggunakan dua pendekatan:

1. **RandomizedSearchCV** — pencarian acak cepat dari ruang parameter luas
2. **Optuna** — optimasi berbasis Bayesian yang lebih cerdas dan efisien

Kedua hasil kemudian dibandingkan secara head-to-head terhadap baseline SVM.
"""

# Install Optuna (hanya perlu dijalankan sekali)
#!pip install optuna -q
print('✅ Optuna siap')

"""### 8.1 Tuning dengan RandomizedSearchCV"""

from sklearn.model_selection import RandomizedSearchCV, StratifiedKFold
from sklearn.svm import SVC
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np

# ── Pipeline: TF-IDF + SVM (cegah data leakage) ──────────────────────────────
pipeline_svm = Pipeline([
    ('tfidf', TfidfVectorizer(
        max_features=5000,
        ngram_range=(1, 2),
        sublinear_tf=True
    )),
    ('clf', SVC(
        class_weight='balanced',
        probability=True,      # dibutuhkan untuk predict_proba nanti
        random_state=42
    ))
])

# ── Ruang Parameter yang Dicari ───────────────────────────────────────────────
param_dist = {
    'tfidf__max_features' : [3000, 5000, 8000],
    'tfidf__ngram_range'  : [(1, 1), (1, 2), (1, 3)],
    'tfidf__min_df'       : [1, 2, 3],
    'clf__C'              : [0.01, 0.1, 0.5, 1, 5, 10, 50],
    'clf__kernel'         : ['linear', 'rbf', 'sigmoid'],
    'clf__gamma'          : ['scale', 'auto'],          # hanya berlaku untuk rbf/sigmoid
}

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

random_search = RandomizedSearchCV(
    estimator=pipeline_svm,
    param_distributions=param_dist,
    n_iter=30,               # coba 30 kombinasi acak
    scoring='f1_weighted',   # multiclass → pakai weighted
    cv=skf,
    verbose=1,
    random_state=42,
    n_jobs=-1
)

print('⏳ Menjalankan RandomizedSearchCV (30 iterasi × 5-fold)...')
random_search.fit(X, y)

print('\n✅ RandomizedSearchCV selesai!')
print('\n📋 Best Parameters:')
for k, v in random_search.best_params_.items():
    print(f'   {k}: {v}')
print(f'\n🎯 Best CV F1-Weighted: {random_search.best_score_:.4f}')

from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score,
    classification_report, confusion_matrix
)
import seaborn as sns
import matplotlib.pyplot as plt

# ── Evaluasi model RandomizedSearch pada test set ────────────────────────────
best_random = random_search.best_estimator_
best_random.fit(X_train, y_train)    # fit ulang dengan seluruh training data
y_pred_random = best_random.predict(X_test)

acc_r   = accuracy_score(y_test, y_pred_random)
prec_r  = precision_score(y_test, y_pred_random, average='weighted', zero_division=0)
rec_r   = recall_score(y_test, y_pred_random, average='weighted', zero_division=0)
f1_r    = f1_score(y_test, y_pred_random, average='weighted', zero_division=0)

print('=' * 55)
print('  HASIL: SVM Tuned (RandomizedSearchCV)')
print('=' * 55)
print(f'  Accuracy  : {acc_r:.4f} ({acc_r*100:.2f}%)')
print(f'  Precision : {prec_r:.4f}')
print(f'  Recall    : {rec_r:.4f}')
print(f'  F1-Score  : {f1_r:.4f}')
print()
print('  Classification Report:')
print(classification_report(y_test, y_pred_random, zero_division=0))

# Confusion matrix
label_kelas = sorted(y_test.unique())
cm_r = confusion_matrix(y_test, y_pred_random, labels=label_kelas)

plt.figure(figsize=(6, 5))
sns.heatmap(cm_r, annot=True, fmt='d', cmap='Blues',
            xticklabels=label_kelas, yticklabels=label_kelas)
plt.title('Confusion Matrix — SVM Tuned (RandomizedSearch)', fontweight='bold')
plt.xlabel('Prediksi')
plt.ylabel('Aktual')
plt.tight_layout()
plt.savefig('cm_svm_random.png', dpi=150, bbox_inches='tight')
plt.show()

"""### 8.2 Tuning dengan Optuna"""

import optuna
from sklearn.model_selection import cross_val_score, StratifiedKFold
from sklearn.svm import SVC
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer

optuna.logging.set_verbosity(optuna.logging.WARNING)  # sembunyikan log berlebih

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

def objective(trial):
    """Fungsi objektif Optuna untuk SVM multiclass sentimen"""

    # ── Suggest parameter TF-IDF ──────────────────────────────────────────────
    max_features  = trial.suggest_categorical('tfidf__max_features', [3000, 5000, 8000])
    ngram_max     = trial.suggest_int('tfidf__ngram_max', 1, 3)   # (1, ngram_max)
    min_df        = trial.suggest_int('tfidf__min_df', 1, 3)

    # ── Suggest parameter SVM ─────────────────────────────────────────────────
    kernel  = trial.suggest_categorical('clf__kernel', ['linear', 'rbf', 'sigmoid'])
    C       = trial.suggest_float('clf__C', 0.01, 50, log=True)
    gamma   = trial.suggest_categorical('clf__gamma', ['scale', 'auto'])

    pipeline = Pipeline([
        ('tfidf', TfidfVectorizer(
            max_features=max_features,
            ngram_range=(1, ngram_max),
            min_df=min_df,
            sublinear_tf=True
        )),
        ('clf', SVC(
            kernel=kernel,
            C=C,
            gamma=gamma,
            class_weight='balanced',
            random_state=42
        ))
    ])

    scores = cross_val_score(
        pipeline, X, y,
        cv=skf,
        scoring='f1_weighted',
        n_jobs=-1
    )
    return scores.mean()

# ── Jalankan Optuna ───────────────────────────────────────────────────────────
study = optuna.create_study(direction='maximize')

print('⏳ Menjalankan Optuna (50 trials × 5-fold)... bisa 5–15 menit')
study.optimize(objective, n_trials=50, show_progress_bar=True)

print('\n✅ Optuna selesai!')
print('\n📋 Best Parameters:')
for k, v in study.best_params.items():
    print(f'   {k}: {v}')
print(f'\n🎯 Best CV F1-Weighted: {study.best_value:.4f}')

# ── Bangun & evaluasi model terbaik Optuna ────────────────────────────────────
bp = study.best_params

best_optuna = Pipeline([
    ('tfidf', TfidfVectorizer(
        max_features=bp['tfidf__max_features'],
        ngram_range=(1, bp['tfidf__ngram_max']),
        min_df=bp['tfidf__min_df'],
        sublinear_tf=True
    )),
    ('clf', SVC(
        kernel=bp['clf__kernel'],
        C=bp['clf__C'],
        gamma=bp['clf__gamma'],
        class_weight='balanced',
        random_state=42
    ))
])

best_optuna.fit(X_train, y_train)
y_pred_optuna = best_optuna.predict(X_test)

acc_o   = accuracy_score(y_test, y_pred_optuna)
prec_o  = precision_score(y_test, y_pred_optuna, average='weighted', zero_division=0)
rec_o   = recall_score(y_test, y_pred_optuna, average='weighted', zero_division=0)
f1_o    = f1_score(y_test, y_pred_optuna, average='weighted', zero_division=0)

print('=' * 55)
print('  HASIL: SVM Tuned (Optuna)')
print('=' * 55)
print(f'  Accuracy  : {acc_o:.4f} ({acc_o*100:.2f}%)')
print(f'  Precision : {prec_o:.4f}')
print(f'  Recall    : {rec_o:.4f}')
print(f'  F1-Score  : {f1_o:.4f}')
print()
print('  Classification Report:')
print(classification_report(y_test, y_pred_optuna, zero_division=0))

# Confusion matrix
cm_o = confusion_matrix(y_test, y_pred_optuna, labels=label_kelas)

plt.figure(figsize=(6, 5))
sns.heatmap(cm_o, annot=True, fmt='d', cmap='Greens',
            xticklabels=label_kelas, yticklabels=label_kelas)
plt.title('Confusion Matrix — SVM Tuned (Optuna)', fontweight='bold')
plt.xlabel('Prediksi')
plt.ylabel('Aktual')
plt.tight_layout()
plt.savefig('cm_svm_optuna.png', dpi=150, bbox_inches='tight')
plt.show()

"""### 8.3 Visualisasi Proses Optimasi Optuna"""

import matplotlib.pyplot as plt
import numpy as np

# ── Plot riwayat nilai F1 setiap trial ───────────────────────────────────────
trial_values = [t.value for t in study.trials if t.value is not None]
best_so_far  = np.maximum.accumulate(trial_values)

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Grafik semua trial
axes[0].plot(trial_values, 'o-', color='#3498db', alpha=0.6, markersize=4, label='F1 per trial')
axes[0].plot(best_so_far, '-', color='#e74c3c', linewidth=2, label='Best so far')
axes[0].axhline(y=study.best_value, color='green', linestyle='--', alpha=0.7,
                label=f'Best = {study.best_value:.4f}')
axes[0].set_xlabel('Trial')
axes[0].set_ylabel('F1-Weighted (CV)')
axes[0].set_title('Riwayat Optimasi Optuna', fontweight='bold')
axes[0].legend()
axes[0].grid(alpha=0.3)

# Distribusi nilai F1 semua trial
axes[1].hist(trial_values, bins=20, color='#9b59b6', alpha=0.8, edgecolor='white')
axes[1].axvline(x=study.best_value, color='red', linestyle='--', linewidth=2,
                label=f'Best = {study.best_value:.4f}')
axes[1].set_xlabel('F1-Weighted Score')
axes[1].set_ylabel('Jumlah Trial')
axes[1].set_title('Distribusi Hasil Trial Optuna', fontweight='bold')
axes[1].legend()
axes[1].grid(alpha=0.3)

plt.suptitle('Analisis Proses Hyperparameter Tuning (Optuna)', fontsize=14, fontweight='bold')
plt.tight_layout()
plt.savefig('optuna_history.png', dpi=150, bbox_inches='tight')
plt.show()

# Top 5 trial terbaik
print('\n🏆 Top 5 Trial Terbaik:')
print('-' * 50)
sorted_trials = sorted(study.trials, key=lambda t: t.value or 0, reverse=True)[:5]
for i, t in enumerate(sorted_trials, 1):
    print(f'  #{i} F1={t.value:.4f} | {t.params}')

"""### 8.4 Perbandingan: Baseline vs RandomizedSearch vs Optuna"""

import pandas as pd

# ── Metrik baseline SVM (dari sel sebelumnya) ─────────────────────────────────
# Pastikan 'hasil_svm' sudah ada dari sel pemodelan sebelumnya
y_pred_baseline = hasil_svm['y_pred']

acc_b   = accuracy_score(y_test, y_pred_baseline)
prec_b  = precision_score(y_test, y_pred_baseline, average='weighted', zero_division=0)
rec_b   = recall_score(y_test, y_pred_baseline, average='weighted', zero_division=0)
f1_b    = f1_score(y_test, y_pred_baseline, average='weighted', zero_division=0)

# ── Tabel Perbandingan ────────────────────────────────────────────────────────
comparison_df = pd.DataFrame({
    'Baseline SVM': {
        'Accuracy' : round(acc_b,  4),
        'Precision': round(prec_b, 4),
        'Recall'   : round(rec_b,  4),
        'F1-Score' : round(f1_b,   4),
    },
    'RandomizedSearchCV': {
        'Accuracy' : round(acc_r,  4),
        'Precision': round(prec_r, 4),
        'Recall'   : round(rec_r,  4),
        'F1-Score' : round(f1_r,   4),
    },
    'Optuna': {
        'Accuracy' : round(acc_o,  4),
        'Precision': round(prec_o, 4),
        'Recall'   : round(rec_o,  4),
        'F1-Score' : round(f1_o,   4),
    }
})

# Kolom selisih vs baseline
comparison_df['Δ RandomSearch'] = (comparison_df['RandomizedSearchCV'] - comparison_df['Baseline SVM']).round(4)
comparison_df['Δ Optuna']       = (comparison_df['Optuna']             - comparison_df['Baseline SVM']).round(4)

print('\n📊 PERBANDINGAN SVM SEBELUM DAN SESUDAH TUNING')
print('=' * 75)
display(comparison_df)

# Tentukan metode tuning terbaik
best_method = comparison_df[['RandomizedSearchCV', 'Optuna']].loc['F1-Score'].idxmax()
print(f'\n🏆 Metode Tuning Terbaik (F1-Score): {best_method}')

import matplotlib.pyplot as plt
import numpy as np

metrics   = ['Accuracy', 'Precision', 'Recall', 'F1-Score']
baseline  = [acc_b,  prec_b,  rec_b,  f1_b ]
rand_vals = [acc_r,  prec_r,  rec_r,  f1_r ]
opt_vals  = [acc_o,  prec_o,  rec_o,  f1_o ]

x = np.arange(len(metrics))
w = 0.25

fig, ax = plt.subplots(figsize=(11, 6))

bars_b = ax.bar(x - w, baseline,  w, label='Baseline SVM',       color='#95a5a6', alpha=0.9)
bars_r = ax.bar(x,     rand_vals, w, label='RandomizedSearchCV',  color='#3498db', alpha=0.9)
bars_o = ax.bar(x + w, opt_vals,  w, label='Optuna',              color='#e74c3c', alpha=0.9)

for bars in [bars_b, bars_r, bars_o]:
    for bar in bars:
        ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.005,
                f'{bar.get_height():.3f}', ha='center', fontsize=8.5, fontweight='bold')

ax.set_xticks(x)
ax.set_xticklabels(metrics, fontsize=12)
ax.set_ylabel('Skor', fontsize=12)
ax.set_ylim(0, 1.12)
ax.set_title('Perbandingan Performa SVM: Baseline vs Tuning', fontsize=14, fontweight='bold')
ax.legend(fontsize=11)
ax.grid(axis='y', alpha=0.3)

plt.tight_layout()
plt.savefig('svm_tuning_comparison.png', dpi=150, bbox_inches='tight')
plt.show()

"""---
## 🏆 Kesimpulan: Sebelum dan Sesudah Hyperparameter Tuning

### Ringkasan Hasil Tuning SVM

| Metrik | Baseline SVM | RandomizedSearchCV | Optuna | Δ RandomSearch | Δ Optuna |
|---|---|---|---|---|---|
| Accuracy | **0,7386** | 0,7377 | 0,7377 | -0,0009 | -0,0009 |
| Precision | **0,7441** | 0,7379 | 0,7392 | -0,0062 | -0,0049 |
| Recall | **0,7386** | 0,7377 | 0,7377 | -0,0009 | -0,0009 |
| F1-Score | **0,7391** | 0,7371 | 0,7376 | -0,0020 | -0,0015 |

### Parameter Terbaik yang Ditemukan

**RandomizedSearchCV:**
- Kernel: RBF, C: 50, Gamma: scale
- TF-IDF: max_features=5000, ngram_range=(1,3), min_df=2
- Best CV F1: 0,7418

**Optuna:**
- Kernel: RBF, C: 6,46, Gamma: scale
- TF-IDF: max_features=8000, ngram_range=(1,1), min_df=2
- Best CV F1: 0,7439

### Analisis Hasil Tuning

Hasil tuning menunjukkan temuan yang menarik — baik RandomizedSearchCV maupun
Optuna **tidak berhasil meningkatkan performa** SVM dibanding baseline.
Selisih penurunannya sangat kecil (≤ 0,002), namun tetap menunjukkan bahwa
konfigurasi default SVM dengan kernel linear dan C=1,0 sudah cukup optimal
untuk dataset ini.

Terdapat beberapa alasan yang menjelaskan fenomena ini:

**1. Baseline sudah mendekati optimal**
SVM dengan kernel linear pada data TF-IDF berdimensi tinggi memang sudah
sangat efisien secara default. Ruang fitur yang sparse (banyak nilai nol)
justru lebih cocok untuk kernel linear dibanding RBF.

**2. Kernel RBF tidak selalu lebih baik untuk teks**
Kedua metode tuning merekomendasikan kernel RBF, namun pada praktiknya
kernel RBF pada data TF-IDF berdimensi tinggi cenderung lebih lambat
dan tidak selalu menghasilkan generalisasi yang lebih baik dibanding
kernel linear.

**3. Keterbatasan data**
Dengan 5.698 tweet dan label yang dihasilkan secara otomatis oleh IndoBERT,
akurasi di atas 73-74% sudah merupakan batas yang wajar mengingat kompleksitas
bahasa informal Twitter yang penuh sarkasme dan ambiguitas.

### Kesimpulan Final

Di antara dua metode tuning yang digunakan, **Optuna menghasilkan performa
lebih baik** dibanding RandomizedSearchCV dengan F1-Score 0,7376 vs 0,7371
dan CV F1 tertinggi 0,7439.

Namun demikian, jika dibandingkan dengan baseline SVM, keduanya belum mampu
melampaui performa awal. Oleh karena itu **SVM (Linear) baseline (C=1,0,
kernel linear)** tetap ditetapkan sebagai model final terbaik dengan:

- **Accuracy : 73,86%**
- **Precision : 74,41%**
- **Recall : 73,86%**
- **F1-Score : 73,91%**
- **CV Score : 0,7350 ± 0,0064**

Hasil ini menunjukkan bahwa konfigurasi default SVM sudah sangat optimal
untuk data teks TF-IDF berdimensi tinggi, dan proses tuning justru
mengkonfirmasi validitas pemilihan SVM sebagai model utama sejak awal.

### 8.5 Simpan Model Terbaik
"""

import pickle

# ── Pilih model terbaik antara RandomSearch vs Optuna ────────────────────────
if f1_o >= f1_r:
    final_model  = best_optuna
    final_method = 'Optuna'
    final_f1     = f1_o
else:
    final_model  = best_random
    final_method = 'RandomizedSearchCV'
    final_f1     = f1_r

print(f'💾 Model terpilih: SVM Tuned ({final_method})')
print(f'   F1-Score: {final_f1:.4f} vs Baseline: {f1_b:.4f}')
print(f'   Peningkatan: {(final_f1 - f1_b):+.4f}')

# Simpan model ke file
with open('svm_tuned_mbg.pkl', 'wb') as f:
    pickle.dump(final_model, f)

print('\n✅ Model tersimpan: svm_tuned_mbg.pkl')

# ── Contoh penggunaan model untuk prediksi baru ───────────────────────────────
print('\n🔍 Contoh Prediksi:')
teks_baru = [
    "program makan bergizi gratis sangat membantu anak sekolah",
    "makan gratis tapi menunya tidak enak sama sekali",
    "sudah dapat info program mbg besok mulai dibagikan"
]

for teks in teks_baru:
    pred = final_model.predict([teks])[0]
    print(f'  Teks  : "{teks}"')
    print(f'  Prediksi: {pred}\n')

"""---
## 📝 Catatan Penting

### ⚠️ Hal yang perlu diperhatikan:

1. **Imbalanced Class**: Jika salah satu kelas jauh lebih sedikit, tambahkan **SMOTE** (oversampling):
   ```python
   from imblearn.over_sampling import SMOTE
   smote = SMOTE(random_state=42)
   X_train_sm, y_train_sm = smote.fit_resample(X_train_tfidf, y_train)
   ```

2. **Hyperparameter Tuning**: Untuk hasil lebih optimal, gunakan GridSearchCV pada SVM:
   ```python
   from sklearn.model_selection import GridSearchCV
   param_grid = {'C': [0.1, 1, 10], 'kernel': ['linear', 'rbf']}
   grid = GridSearchCV(SVC(), param_grid, cv=5, scoring='f1_weighted')
   grid.fit(X_train_tfidf, y_train)
   ```

"""
